# Place this at .github/workflows/nodejs.yml
name: Node.js CI (Node 22)

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Display Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Setup Firebase Service Account (if present)
        if: secrets.FIREBASE_SERVICE_ACCOUNT_JSON != ''
        run: |
          printf '%s' "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" > $GITHUB_WORKSPACE/firebase-sa.json
          chmod 600 $GITHUB_WORKSPACE/firebase-sa.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/firebase-sa.json" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          CI: true
