# Place this at .github/workflows/nodejs.yml
name: Node.js CI (Node 22)

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Display Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Decode Firebase Service Account (if present)
        if: env.FIREBASE_SERVICE_ACCOUNT_JSON != ''
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" | base64 -d > $GITHUB_WORKSPACE/firebase-sa.json
          chmod 600 $GITHUB_WORKSPACE/firebase-sa.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        if: env.FIREBASE_SERVICE_ACCOUNT_JSON != ''
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/firebase-sa.json" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          CI: true
