name: Test GCP OIDC auth
on:
  workflow_dispatch:

permissions:
  id-token: write      # required so GitHub injects the OIDC token
  contents: read       # common helper permission for checkout/actions

jobs:
  auth-test:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GCP using Workload Identity
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Verify identity
        run: |
          gcloud auth list
